"""add_receipt_number_to_digital_receipts

Revision ID: 412f3f3fd433
Revises: da10b64b9abc
Create Date: 2026-05-02 20:51:09.191568
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '412f3f3fd433'
down_revision: Union[str, None] = 'da10b64b9abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_foreign_key(None, 'charging_sessions', 'reservation', ['reservation_id'], ['id'])
    # Add receipt_number as nullable first, backfill, then set NOT NULL
    op.add_column('digital_receipts', sa.Column('receipt_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE digital_receipts SET receipt_number = 'RCP-LEGACY-' || id WHERE receipt_number IS NULL")
    op.alter_column('digital_receipts', 'receipt_number', nullable=False)
    op.create_index(op.f('ix_digital_receipts_receipt_number'), 'digital_receipts', ['receipt_number'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digital_receipts_receipt_number'), table_name='digital_receipts')
    op.drop_column('digital_receipts', 'receipt_number')
    op.drop_constraint(None, 'charging_sessions', type_='foreignkey')
    # ### end Alembic commands ###
